import type { OpenCrocConfig } from '../types.js';

/**
 * Generate global-teardown.ts content for Playwright.
 * Handles cleanup endpoint call and optional SQL cleanup.
 */
export function generateGlobalTeardown(config: OpenCrocConfig): string {
  const pw = config.playwright ?? {};
  const rt = config.runtime ?? {};
  const baseURL = pw.baseURL || '';

  const hasCleanupEndpoint = !!rt.db?.cleanupEndpoint;
  const hasCleanupFile = !!rt.db?.cleanupFile;

  const lines: string[] = [];

  lines.push(`/**`);
  lines.push(` * Global teardown — generated by OpenCroc.`);
  lines.push(` * Runs once after all test projects complete.`);
  lines.push(` */`);
  lines.push('');
  lines.push(`const BASE_URL = process.env.BASE_URL || '${baseURL || 'http://localhost:3000'}';`);
  lines.push('');

  lines.push(`export default async function globalTeardown(): Promise<void> {`);
  lines.push(`  console.log('[global-teardown] Starting...');`);
  lines.push('');

  if (hasCleanupEndpoint) {
    lines.push(`  // Cleanup via backend endpoint`);
    lines.push(`  try {`);
    lines.push(`    await fetch(\`\${BASE_URL}${rt.db!.cleanupEndpoint}\`, { method: 'POST' });`);
    lines.push(`    console.log('[global-teardown] Cleanup endpoint called.');`);
    lines.push(`  } catch {`);
    lines.push(`    console.warn('[global-teardown] Cleanup endpoint failed.');`);
    lines.push(`  }`);
    lines.push('');
  }

  if (hasCleanupFile) {
    lines.push(`  // SQL cleanup file execution (placeholder — wire to your DB helper)`);
    lines.push(`  // import { executeSeedSQL } from './utils/db-helper';`);
    lines.push(`  // await executeSeedSQL('${rt.db!.cleanupFile}');`);
    lines.push('');
  }

  lines.push(`  console.log('[global-teardown] Done.');`);
  lines.push(`}`);
  lines.push('');

  return lines.join('\n');
}
