import type { OpenCrocConfig } from '../types.js';

/**
 * Generate global-setup.ts content for Playwright.
 * Handles backend readiness probe, seed endpoint call, and log cleanup.
 */
export function generateGlobalSetup(config: OpenCrocConfig): string {
  const pw = config.playwright ?? {};
  const rt = config.runtime ?? {};
  const baseURL = pw.baseURL || '';

  const hasSeedEndpoint = !!rt.db?.seedEndpoint;
  const hasLogEndpoint = !!rt.logEndpoint;
  const hasSeedFile = !!rt.db?.seedFile;

  const lines: string[] = [];

  lines.push(`/**`);
  lines.push(` * Global setup — generated by OpenCroc.`);
  lines.push(` * Runs once before all test projects.`);
  lines.push(` */`);
  lines.push('');
  lines.push(`const BASE_URL = process.env.BASE_URL || '${baseURL || 'http://localhost:3000'}';`);
  lines.push('');

  // fetchWithRetry helper
  lines.push(`async function fetchWithRetry(`);
  lines.push(`  url: string,`);
  lines.push(`  options: RequestInit,`);
  lines.push(`  retries = 3,`);
  lines.push(`): Promise<Response | null> {`);
  lines.push(`  for (let i = 0; i < retries; i++) {`);
  lines.push(`    try {`);
  lines.push(`      const resp = await fetch(url, { ...options, signal: AbortSignal.timeout(10_000) });`);
  lines.push(`      if (resp.ok) return resp;`);
  lines.push(`      console.warn(\`[global-setup] \${options.method} \${url} → \${resp.status} (\${i + 1}/\${retries})\`);`);
  lines.push(`    } catch (err: unknown) {`);
  lines.push(`      const msg = err instanceof Error ? err.message : String(err);`);
  lines.push(`      console.warn(\`[global-setup] \${options.method} \${url} error (\${i + 1}/\${retries}): \${msg}\`);`);
  lines.push(`    }`);
  lines.push(`    if (i < retries - 1) await new Promise((r) => setTimeout(r, 1000 * Math.pow(2, i)));`);
  lines.push(`  }`);
  lines.push(`  return null;`);
  lines.push(`}`);
  lines.push('');

  // waitForBackend helper
  lines.push(`async function waitForBackend(origin: string, timeoutMs = 30_000): Promise<void> {`);
  lines.push(`  const start = Date.now();`);
  lines.push(`  while (Date.now() - start < timeoutMs) {`);
  lines.push(`    try {`);
  lines.push(`      const res = await fetch(\`\${origin}/health\`, { signal: AbortSignal.timeout(3_000) });`);
  lines.push(`      if (res.ok) return;`);
  lines.push(`    } catch {`);
  lines.push(`      // not ready yet`);
  lines.push(`    }`);
  lines.push(`    await new Promise((r) => setTimeout(r, 1_000));`);
  lines.push(`  }`);
  lines.push(`  throw new Error(\`Backend not ready after \${timeoutMs}ms\`);`);
  lines.push(`}`);
  lines.push('');

  // Main function
  lines.push(`export default async function globalSetup(): Promise<void> {`);
  lines.push(`  console.log('[global-setup] Starting...');`);
  lines.push('');
  lines.push(`  // Backend readiness probe`);
  lines.push(`  try {`);
  lines.push(`    await waitForBackend(BASE_URL, 30_000);`);
  lines.push(`    console.log('[global-setup] Backend is ready.');`);
  lines.push(`  } catch (e: unknown) {`);
  lines.push(`    console.warn(\`[global-setup] \${e instanceof Error ? e.message : String(e)}\`);`);
  lines.push(`  }`);
  lines.push('');

  if (hasSeedEndpoint) {
    lines.push(`  // Seed data via backend endpoint`);
    lines.push(`  try {`);
    lines.push(`    await fetchWithRetry(`);
    lines.push(`      \`\${BASE_URL}${rt.db!.seedEndpoint}\`,`);
    lines.push(`      { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: '{}' },`);
    lines.push(`    );`);
    lines.push(`    console.log('[global-setup] Seed endpoint called.');`);
    lines.push(`  } catch {`);
    lines.push(`    console.warn('[global-setup] Seed endpoint failed.');`);
    lines.push(`  }`);
    lines.push('');
  }

  if (hasLogEndpoint) {
    lines.push(`  // Clear test logs`);
    lines.push(`  try {`);
    lines.push(`    await fetchWithRetry(\`\${BASE_URL}${rt.logEndpoint}\`, { method: 'DELETE' });`);
    lines.push(`    console.log('[global-setup] Test logs cleared.');`);
    lines.push(`  } catch {`);
    lines.push(`    console.warn('[global-setup] Failed to clear test logs.');`);
    lines.push(`  }`);
    lines.push('');
  }

  if (hasSeedFile) {
    lines.push(`  // SQL seed file execution (placeholder — wire to your DB helper)`);
    lines.push(`  // import { executeSeedSQL } from './utils/db-helper';`);
    lines.push(`  // await executeSeedSQL('${rt.db!.seedFile}');`);
    lines.push('');
  }

  lines.push(`  console.log('[global-setup] Done.');`);
  lines.push(`}`);
  lines.push('');

  return lines.join('\n');
}
