import { describe, it, expect } from 'vitest';
import { generatePlaywrightConfig } from './playwright-config-generator.js';
import { generateGlobalSetup } from './global-setup-generator.js';
import { generateGlobalTeardown } from './global-teardown-generator.js';
import { generateAuthSetup } from './auth-setup-generator.js';
import type { OpenCrocConfig } from '../types.js';

describe('runtime generators', () => {
  const baseConfig: OpenCrocConfig = {
    backendRoot: './backend',
    outDir: './e2e-output',
    playwright: {
      baseURL: 'http://localhost:4000',
      timeout: 60_000,
    },
  };

  // ===== Playwright Config Generator =====

  describe('generatePlaywrightConfig', () => {
    it('generates basic config without auth', () => {
      const result = generatePlaywrightConfig(baseConfig);

      expect(result).toContain("import { defineConfig, devices } from '@playwright/test'");
      expect(result).toContain("testDir: './e2e-output'");
      expect(result).toContain("baseURL: 'http://localhost:4000'");
      expect(result).toContain('timeout: 60000');
      expect(result).toContain("globalSetup: './global-setup.ts'");
      expect(result).toContain("globalTeardown: './global-teardown.ts'");
      // Without auth → single chromium project, no setup project
      expect(result).toContain("name: 'chromium'");
      expect(result).not.toContain("name: 'setup'");
      expect(result).not.toContain('storageState');
    });

    it('generates auth projects when loginUrl is set', () => {
      const config: OpenCrocConfig = {
        ...baseConfig,
        runtime: {
          auth: {
            loginUrl: '/api/auth/login',
            storageStatePath: 'pw/.auth/state.json',
          },
        },
      };
      const result = generatePlaywrightConfig(config);

      expect(result).toContain("name: 'setup'");
      expect(result).toContain("testMatch: '**/auth.setup.ts'");
      expect(result).toContain("name: 'chromium'");
      expect(result).toContain("dependencies: ['setup']");
      expect(result).toContain("storageState: 'pw/.auth/state.json'");
      expect(result).toContain("name: 'chromium-no-auth'");
    });

    it('uses default baseURL when not specified', () => {
      const result = generatePlaywrightConfig({ backendRoot: '.' });
      expect(result).toContain("process.env.BASE_URL || 'http://localhost:3000'");
    });

    it('includes extra projects', () => {
      const config: OpenCrocConfig = {
        ...baseConfig,
        runtime: {
          extraProjects: [
            { name: 'seed-health', testMatch: '**/seed-health.test.ts', dependencies: ['setup'] },
          ],
        },
      };
      const result = generatePlaywrightConfig(config);
      expect(result).toContain("name: 'seed-health'");
      expect(result).toContain("testMatch: '**/seed-health.test.ts'");
      expect(result).toContain("dependencies: ['setup']");
    });

    it('respects workers and retries overrides', () => {
      const config: OpenCrocConfig = {
        ...baseConfig,
        playwright: { ...baseConfig.playwright, workers: 8, retries: 3 },
      };
      const result = generatePlaywrightConfig(config);
      expect(result).toContain('retries: 3');
      expect(result).toContain('workers: 8');
    });
  });

  // ===== Global Setup Generator =====

  describe('generateGlobalSetup', () => {
    it('generates basic setup with backend probe', () => {
      const result = generateGlobalSetup(baseConfig);

      expect(result).toContain('Global setup — generated by OpenCroc');
      expect(result).toContain("BASE_URL = process.env.BASE_URL || 'http://localhost:4000'");
      expect(result).toContain('waitForBackend');
      expect(result).toContain('export default async function globalSetup');
    });

    it('includes seed endpoint call when configured', () => {
      const config: OpenCrocConfig = {
        ...baseConfig,
        runtime: {
          db: { seedEndpoint: '/internal/e2e/seed' },
        },
      };
      const result = generateGlobalSetup(config);
      expect(result).toContain('/internal/e2e/seed');
      expect(result).toContain('Seed endpoint called');
    });

    it('includes log cleanup when configured', () => {
      const config: OpenCrocConfig = {
        ...baseConfig,
        runtime: { logEndpoint: '/internal/test-logs' },
      };
      const result = generateGlobalSetup(config);
      expect(result).toContain('/internal/test-logs');
      expect(result).toContain("method: 'DELETE'");
    });

    it('omits seed and log sections when not configured', () => {
      const result = generateGlobalSetup(baseConfig);
      expect(result).not.toContain('Seed endpoint');
      expect(result).not.toContain('test-logs');
    });
  });

  // ===== Global Teardown Generator =====

  describe('generateGlobalTeardown', () => {
    it('generates basic teardown', () => {
      const result = generateGlobalTeardown(baseConfig);

      expect(result).toContain('Global teardown — generated by OpenCroc');
      expect(result).toContain('export default async function globalTeardown');
    });

    it('includes cleanup endpoint when configured', () => {
      const config: OpenCrocConfig = {
        ...baseConfig,
        runtime: {
          db: { cleanupEndpoint: '/internal/e2e/cleanup' },
        },
      };
      const result = generateGlobalTeardown(config);
      expect(result).toContain('/internal/e2e/cleanup');
      expect(result).toContain("method: 'POST'");
    });

    it('omits cleanup section when not configured', () => {
      const result = generateGlobalTeardown(baseConfig);
      expect(result).not.toContain('cleanup');
    });
  });

  // ===== Auth Setup Generator =====

  describe('generateAuthSetup', () => {
    it('generates API-based auth when loginUrl is set', () => {
      const config: OpenCrocConfig = {
        ...baseConfig,
        runtime: {
          auth: {
            loginUrl: '/api/auth/login',
            username: 'testAdmin',
            password: 'secret123',
          },
        },
      };
      const result = generateAuthSetup(config);

      expect(result).toContain("import { test as setup, expect } from '@playwright/test'");
      expect(result).toContain("'/api/auth/login'");
      expect(result).toContain("'testAdmin'");
      expect(result).toContain('request.post(loginUrl');
      expect(result).toContain('storageState');
      // Should NOT contain browser-based flow
      expect(result).not.toContain('browser.newContext()');
    });

    it('generates browser-based auth placeholder when no loginUrl', () => {
      const result = generateAuthSetup(baseConfig);

      expect(result).toContain('browser.newContext()');
      expect(result).toContain('TODO: Implement your login flow');
      expect(result).toContain('context.storageState');
    });

    it('uses custom storageStatePath', () => {
      const config: OpenCrocConfig = {
        ...baseConfig,
        runtime: {
          auth: {
            loginUrl: '/login',
            storageStatePath: 'custom/.auth/state.json',
          },
        },
      };
      const result = generateAuthSetup(config);
      expect(result).toContain("'custom/.auth/state.json'");
    });

    it('defaults username to admin', () => {
      const config: OpenCrocConfig = {
        ...baseConfig,
        runtime: { auth: { loginUrl: '/login' } },
      };
      const result = generateAuthSetup(config);
      expect(result).toContain("'admin'");
    });
  });
});
